# Generated by Django 5.1 on 2024-08-31 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('organizers', models.ManyToManyField(related_name='events_organizations', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='events_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=255)),
                ('organizers', models.ManyToManyField(related_name='projects_organizations', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='projects_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
