# Generated by Django 5.1 on 2024-08-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('workplace', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='event',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='project',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='event',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='second_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='address',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='login',
        ),
        migrations.AddField(
            model_name='event',
            name='students',
            field=models.ManyToManyField(related_name='events', to='students.student'),
        ),
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(related_name='projects', to='students.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='staff',
            field=models.ManyToManyField(related_name='events', to='students.staff'),
        ),
        migrations.AddField(
            model_name='project',
            name='staff',
            field=models.ManyToManyField(related_name='projects', to='students.staff'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
