# Generated by Django 5.1 on 2024-08-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_event_staff_remove_project_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='course',
        ),
    ]
